stages:
  - image
  - registry

build:
  stage: image
  script:
    - make docker-build
    - make test
  tags:
    - mediaio

push:
  stage: registry
  script:
    - make docker-push-registry
    - make docker-clean
  tags:
    - mediaio
