stages:
  - image
  - registry

build-rs:
  stage: image
  script:
    - make docker-build-rs
    - make test-rs
  tags:
    - mediaio

build-clang:
  stage: image
  script:
    - make docker-build-clang
    - make test-clang
  tags:
    - mediaio

push-rs:
  stage: registry
  script:
    - make docker-push-registry-rs
    - make docker-clean-rs
  tags:
    - mediaio

push-clang:
  stage: registry
  script:
    - make docker-push-registry-clang
    - make docker-clean-clang
  tags:
    - mediaio
